services:
  db:
    image: postgres:14
    env_file: .env
    environment:
      - POSTGRES_DB=conduit
      - POSTGRES_USER=conduit
      - POSTGRES_PASSWORD=conduit123
      - TZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - conduit-net

  backend:
    build: ./conduit-backend
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_DB: conduit
      POSTGRES_USER: conduit
      POSTGRES_PASSWORD: conduit123
    ports:
      - "8000:5000"
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             gunicorn -w 4 -b 0.0.0.0:5000 conduit.wsgi:application"
    depends_on:
      - db
    networks:
      - conduit-net

  frontend:
    build:
      context: ./conduit-frontend
      args:
        - REACT_APP_API_URL=http://116.203.194.189:8000/api
    ports:
      - "8282:80"
    restart: on-failure
    depends_on:
      - backend
    networks:
      - conduit-net

volumes:
  postgres_data:

networks:
  conduit-net:
