name: Conduit Deployment

on:
  push:
    branches: [ conduit-deployment ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Login to GHCR
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build & Push Backend
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./conduit-backend
          push: true
          tags: ghcr.io/ibog1/conduit-backend:latest
      
      - name: Build & Push Frontend
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./conduit-frontend
          push: true
          tags: ghcr.io/ibog1/conduit-frontend:latest

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      
      - name: Generate .env
        run: |
          cat > .env << EOF
          # Database (Postgres)
          POSTGRES_DB=conduit
          POSTGRES_USER=conduit
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL=postgresql://conduit:${{ secrets.POSTGRES_PASSWORD }}@db:5432/conduit

          # Django Backend
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_PW }}
          DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_EMAIL }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_USER }}
          DJANGO_ALLOWED_HOSTS='${{ secrets.SERVER_IP }},localhost,127.0.0.1,*'
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=${{ secrets.DEBUG }}

          # CORS
          CORS_ORIGINS=localhost:8282,127.0.0.1:8282,${{ secrets.SERVER_IP }}:8282

          # Frontend
          FRONTEND_PRODUCTION=${{ secrets.production }}
          FRONTEND_APIURL=${{ secrets.apiurl }}
          EOF

      - name: Copy docker-compose.yaml + .env to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./docker-compose.yaml,.env"
          target: "/home/ibrahim-guellue/conduit-docker-compose"


      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker login ghcr.io -u ibog1 --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
            cd /home/ibrahim-guellue/conduit-docker-compose
            docker compose down
            docker compose up -d
